#include <PacketErr.h>
#include <Protocols.h>

/** Packet payload type **/
union packet_pl_t{
    int general;//General name label to attach data to
    /** Add all protocol data type generated by protobuf here**/
}

/** Pakcet header type **/
struct packet_hd_t{
    int len;
    int cmd;
}

struct packet_t{    
    packet_t(int cmd);
    int parse_header(const char * header); 
    int parse_payload(const char * payload);

    struct packet_hd_t hd;
    union packet_pl_t pl;
};

#define PACKET_HD_SIZE sizeof(struct packet_hd_t)
